// flow-typed signature: 391df0c85bb3b70a3bd9c43cd4063842
// flow-typed version: <<STUB>>/uws_v^0.14.5/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uws/uws' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uws/uws.js' {
  declare module.exports: $Exports<'uws/uws'>;
}
